### ISSUE TITLE
Problem with weight forwarding

### ISSUE THREAD

**Issue by Suppersine** [VeritasYin/STGCN_IJCAI-18#60]
I got a weight error in your model after running this:

!python main.py --n_route 228 --graph {%weight_matrix.csv%}

`WARNING:tensorflow:From main.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From main.py:18: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2021-12-29 08:21:54.294853: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-12-29 08:21:54.300115: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2299995000 Hz
2021-12-29 08:21:54.300391: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55bf0b218a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-12-29 08:21:54.300431: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-12-29 08:21:54.302392: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-12-29 08:21:54.435288: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 08:21:54.436219: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55bf0b218f40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-12-29 08:21:54.436288: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla K80, Compute Capability 3.7
2021-12-29 08:21:54.436480: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 08:21:54.437232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
2021-12-29 08:21:54.437601: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-12-29 08:21:54.438982: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-12-29 08:21:54.440230: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-12-29 08:21:54.440614: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-12-29 08:21:54.442478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-12-29 08:21:54.443777: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-12-29 08:21:54.447963: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-12-29 08:21:54.448094: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 08:21:54.448935: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 08:21:54.449683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2021-12-29 08:21:54.449769: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-12-29 08:21:54.451071: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-12-29 08:21:54.451170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2021-12-29 08:21:54.451224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2021-12-29 08:21:54.451457: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 08:21:54.452304: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-12-29 08:21:54.453078: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10813 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
Training configs: Namespace(batch_size=50, epoch=50, graph='{%weight_matrix.csv%}', inf_mode='merge', ks=3, kt=3, lr=0.001, n_his=12, n_pred=9, n_route=228, opt='RMSProp', save=10)
ERROR: input file was not found in ./dataset/{%weight_matrix.csv%}.
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    W = weight_matrix(pjoin('./dataset', args.graph))
  File "/content/STGCN_IJCAI-18/utils/math_graph.py", line 86, in weight_matrix
    if set(np.unique(W)) == {0, 1}:
UnboundLocalError: local variable 'W' referenced before assignment`

**Comment by VeritasYin** [comment]
The parameter `graph` takes the file path of customized weight matrix as input. You need replace '{%weight_matrix.csv%}' by your own file. It is not required if you would like to simply run PeMSD7-M.
