### ISSUE TITLE
pickle data was truncated

### ISSUE THREAD

**Issue by qiuelk12138** [VeritasYin/STGCN_IJCAI-18#67]
Hello, thank you so much for making this data public!
I have a question that when I was training the model, I ran one epoch and encountered the following error:
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
File "", line 1, in
File "D:\anaconda\envs\mmd\lib\multiprocessing\spawn.py", line 116, in spawn_main
exitcode = _main(fd, parent_sentinel)
File "D:\anaconda\envs\mmd\lib\multiprocessing\spawn.py", line 126, in _main
self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

**Comment by HHeracles** [comment]
May I ask how you solved this problem?
